from datetime import timedelta


DEBUG = False
SECRET_KEY = ''
PERMANENT_SESSION_LIFETIME = timedelta(days=7)
LOGS_BASE_FILENAME = ''

SQLALCHEMY_DATABASE_URI = ''
SQLALCHEMY_ECHO = False
SQLALCHEMY_TRACK_MODIFICATIONS = False

DIRECT_CLIENT_ID = ''
DIRECT_CLIENT_SECRET = ''
DIRECT_OAUTH_TOKEN = ''

SENDER_LOGIN = ''
SENDER_PASSWORD = ''
SENDER_EMAIL = ''
SENDER_TO = []
SENDER_SMS_TO = []
